config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  # Defines the root path route ("/")
  # root "articles#index"

  # get "home", to: "pages#home"
  get "about", to: "pages#about", as: :about
  get "contact", to: "pages#contact", as: :contact
  get "search", to: "pages#search", as: :search
  # VERB "PAGE_NAME", to: "CONTROLLER#ACTION"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
    @names = %w[raquel anne fabio marcelo george]
  end

  def contact
    @email = params[:email]
    @message = params[:message]
  end

  def search
    @letter = params[:name]
    @names = %w[raquel anne fabio marcelo george]
    if params[:name]
      @names = @names.select { |member| member.start_with?(params[:name].downcase) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
    </nav>
    
    <%= yield %>

    <footer>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<ul>
    <li>Email: </li>
    <li>Telefone: </li>
    <li>Endereço: </li>
</ul>

<ul>
<% @names.each do |student| %>
  <li class="active"><%= student.capitalize %></li>  
<% end %>
</ul>

app/views/pages/contact.html.erb
<form action="/contact" method="get">
    <label>E-mail</label>
    <input type="text" name="email" placeholder="email@example.com">
    <label>Feedback</label>
    <input type="text-area" name="message" placeholder="Write your feedback">
    <input type="submit">
</form>

<% if @email && @message %>
  <p>Your message:</p>
  <%= @message %>
  <%= @email %>
<% end %>

app/views/pages/home.html.erb
<h1>Hello World!</h1>

<p>Welcome to this wonderful website!</p>

<p>Now is <%= Time.now %></p>

<ul>
    <li><%= link_to "More info about Contact", contact_path, class: "btn btn-primary" %></li>
    <li><%= link_to "More info about Us", about_path, class: "btn btn-danger" %></li>
</ul>

app/views/pages/search.html.erb
<form action="/search" method="get">
  <input type="text" name="name" value="<%= @letter %>" placeholder="Who are you looking for?">
  <input type="submit">
</form>

<p>You are looking for <strong><%= @letter %></strong>:</p>

<% @names.each do |name| %>
  <%= name.capitalize %>
<% end %>